"""
CSV Logger for Confidence-Score Based Sensor Fusion Simulation
==============================================================

Exports the full time-series data generated by `notebooks/fusion_development.ipynb`
to a CSV file for external analysis, plotting, or archival.

Usage (add a cell in the notebook after the fusion step):
--------------------------------------------------------------
    from antenna_fusion.csv_export import export_timeseries_to_csv

    export_timeseries_to_csv(
        filepath="simulation_output.csv",  # or omit for auto-timestamped name
        t=t,
        theta_true=theta_true,
        theta_enc=theta_enc,
        theta_ahrs=theta_ahrs,
        theta_fused=theta_fused,
        conf_enc=c_enc,
        conf_ahrs=c_ahrs,
        # Optional — pass these if you have them; they'll be computed otherwise
        err_enc=err_enc,
        err_ahrs=err_ahrs,
        err_fused=err_fused,
    )
"""

import csv
import os
from datetime import datetime

import numpy as np

from .paths import LOGS_DIR


def export_timeseries_to_csv(
    t,
    theta_true,
    theta_enc,
    theta_ahrs,
    theta_fused,
    conf_enc,
    conf_ahrs,
    err_enc=None,
    err_ahrs=None,
    err_fused=None,
    filepath=None,
    output_dir=None,
    float_precision=6,
):
    """Export the full sensor-fusion time-series to a CSV file.

    Parameters
    ----------
    t : np.ndarray
        Time vector (seconds).
    theta_true : np.ndarray
        Ground-truth angle (degrees).
    theta_enc : np.ndarray
        Encoder sensor reading (degrees).
    theta_ahrs : np.ndarray
        AHRS sensor reading (degrees).
    theta_fused : np.ndarray
        Fused output angle (degrees).
    conf_enc : np.ndarray
        Normalized confidence weight for the encoder.
    conf_ahrs : np.ndarray
        Normalized confidence weight for the AHRS.
    err_enc : np.ndarray or None
        Encoder error (encoder − true). Computed if not supplied.
    err_ahrs : np.ndarray or None
        AHRS error (AHRS − true). Computed if not supplied.
    err_fused : np.ndarray or None
        Fused error (fused − true). Computed if not supplied.
    filepath : str or None
        Full path (including filename) for the output CSV.
        If *None*, an auto-timestamped name is generated.
    output_dir : str or None
        Directory to write the CSV into.  Only used when *filepath*
        is None.  Defaults to the project's ``logs/`` folder.
    float_precision : int
        Number of decimal places for floating-point values.

    Returns
    -------
    str
        The absolute path of the written CSV file.
    """

    # ── Compute errors if not supplied ────────────────────────────────────
    if err_enc is None:
        err_enc = np.asarray(theta_enc) - np.asarray(theta_true)
    if err_ahrs is None:
        err_ahrs = np.asarray(theta_ahrs) - np.asarray(theta_true)
    if err_fused is None:
        err_fused = np.asarray(theta_fused) - np.asarray(theta_true)

    # ── Resolve output path ───────────────────────────────────────────────
    if filepath is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"sim_timeseries_{timestamp}.csv"
        if output_dir is None:
            output_dir = LOGS_DIR
        os.makedirs(output_dir, exist_ok=True)
        filepath = os.path.join(output_dir, filename)

    filepath = os.path.abspath(filepath)

    # ── Build column definitions ──────────────────────────────────────────
    columns = [
        ("time_s",            t),
        ("theta_true_deg",    theta_true),
        ("theta_enc_deg",     theta_enc),
        ("theta_ahrs_deg",    theta_ahrs),
        ("theta_fused_deg",   theta_fused),
        ("conf_enc",          conf_enc),
        ("conf_ahrs",         conf_ahrs),
        ("error_enc_deg",     err_enc),
        ("error_ahrs_deg",    err_ahrs),
        ("error_fused_deg",   err_fused),
    ]

    headers = [name for name, _ in columns]
    arrays  = [np.asarray(arr) for _, arr in columns]

    n_rows = len(arrays[0])
    fmt = f"{{:.{float_precision}f}}"

    # ── Write CSV ─────────────────────────────────────────────────────────
    os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)

    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(headers)

        for i in range(n_rows):
            row = [fmt.format(arr[i]) for arr in arrays]
            writer.writerow(row)

    print(f"[csv_export] Exported {n_rows} rows  →  {filepath}")
    return filepath
